/*
 * EbayBuyerPanel.java
 *
 * Created on August 22, 2006, 9:31 PM
 */

package com.thornapple.ebay.manager.ui;

import com.jhlabs.image.BrushedMetalFilter;
import com.jhlabs.image.MotionBlurFilter;
import com.jhlabs.image.NoiseFilter;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.geom.Point2D;
import org.jdesktop.swingx.painter.ImageEffect;
import org.jdesktop.swingx.painter.gradient.BasicGradientPainter;

/**
 *
 * @author  Bill
 */
public class EbayBuyerPanel extends javax.swing.JPanel {
    
    /** Creates new form EbayBuyerPanel */
    public EbayBuyerPanel() {
        initComponents();
        BasicGradientPainter gradient = new BasicGradientPainter(
                new GradientPaint(new Point2D.Double(0.0, 0.0), Color.WHITE,
                new Point2D.Double(0.0, 1.0), Color.WHITE));
        NoiseFilter noise = new NoiseFilter();
        noise.setDistribution(NoiseFilter.GAUSSIAN);
        noise.setMonochrome(true);
        MotionBlurFilter blur = new MotionBlurFilter();
        blur.setDistance(20.0f);
        BrushedMetalFilter metal = new BrushedMetalFilter();
        metal.setMonochrome(false);
        gradient.setEffects(new ImageEffect(noise),
                new ImageEffect(blur));
        gradient.setUseCache(true);
        this.jXPanel1.setBackgroundPainter(gradient);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jXPanel1 = new org.jdesktop.swingx.JXPanel();

        org.jdesktop.layout.GroupLayout jXPanel1Layout = new org.jdesktop.layout.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jXPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jXPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXPanel jXPanel1;
    // End of variables declaration//GEN-END:variables
    
}
