/*
 * ItemListForm.java
 *
 * Created on August 4, 2006, 10:37 PM
 */

package com.thornapple.ebay.manager.ui;

import binding.BindingContext;
import binding.BindingDescription;
import com.thornapple.ebay.manager.AuctionItem;
import com.thornapple.ebay.manager.ItemSearchCriteria;
import com.thornapple.ebay.manager.adapter.EbayItemAdapter;
import java.awt.BorderLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JWindow;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author  Bill
 */
public class ItemListForm extends javax.swing.JPanel {
    
    private ItemSearchCriteria criteria = new ItemSearchCriteria();
    private BindingContext context = new BindingContext();
    
    private JFrame detailPopup = new JFrame();
    
    /** Creates new form ItemListForm */
    public ItemListForm() {
        initComponents();
        bindComponents();
        detailPopup.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent e) {
                if (detailPopup.isVisible())detailPopup.setVisible(false);
            }
            public void mouseEntered(MouseEvent e) {
            }
            public void mouseExited(MouseEvent e) {
                
            }
            
            public void mousePressed(MouseEvent e) {
            }
            public void mouseReleased(MouseEvent e) {
            }
        });
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Search for:");

        btnSearch.setText("Find It!");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(16, 16, 16)
                        .add(txtSearch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnSearch)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(txtSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnSearch))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        EbayItemAdapter ebaySearch = new EbayItemAdapter();
        context.commitUncommittedValues();
        
        try {
            criteria.setQuery(txtSearch.getText());
            List<AuctionItem> results = ebaySearch.findItems(criteria);
            DefaultListModel model = new DefaultListModel();
            for (AuctionItem item : results) {
                model.addElement(item);
            }
            jList1.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    
    private void bindComponents() {
        context.addDescription(new BindingDescription(criteria, "query",txtSearch, "text"));
        context.bind();
        
        jList1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                detailPopup = new JFrame();
                //detailPopup.add(new JLabel("asdfsdf"),BorderLayout.CENTER);
                
                String itemID = ((AuctionItem)jList1.getSelectedValue()).getItem().getItemID().getValue();
                AuctionItem item;
                try {
                    item = new EbayItemAdapter().getItemDetails(itemID);
                    //item = (AuctionItem)jList1.getSelectedValue();
                    detailPopup.add(new AuctionForm((item)),BorderLayout.CENTER);
                    detailPopup.setSize(getWidth()+50,getHeight()+50);
                    detailPopup.setLocationRelativeTo(jList1);
                    detailPopup.setVisible(true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    
}
